export const routes = {
  addAttribute: "/attributes/new",
  addBrand: "/brands/new",
  addCategory: "/categories/new",
  addCoupon: "/coupons/new",
  addOrder: "/orders/new",
  addProduct: "/products/new",
  addUser: "/users/new",
  attributes: "/attributes",
  brands: "/brands",
  categories: "/categories",
  coupons: "/coupons",
  createRole: "/roles/new",
  currencyRates: "/localization/currency-rates",
  customers: "/customers",
  dashboard: "/",
  editBrand: "/brands/demo/edit",
  editCategory: "/categories/demo/edit",
  editCoupon: "/coupons/demo/edit",
  editOrder: "/orders/demo/edit",
  editProduct: "/products/demo/edit",
  history: "/history",
  integrations: "/integrations",
  listPage: "/list-page",
  media: "/media",
  notifications: "/notifications",
  orderDetail: "/orders/demo",
  orders: "/orders",
  paymentSettings: "/settings/payments",
  permissionSettings: "/settings/permissions",
  productReviews: "/product-reviews",
  products: "/products",
  reports: "/reports",
  roles: "/roles",
  settings: "/settings",
  shippingSettings: "/settings/shipping",
  signIn: "/signin",
  forgotPassword: "/forgot-password",
  supportTickets: "/support-tickets",
  tax: "/tax",
  translation: "/localization/translation",
  updateApp: "/update-app",
  upgrade: "/upgrade",
} as const;

export const pathBuilders = {
  editAttribute: (id: string) => `/attributes/${id}/edit`,
  editBrand: (id: string) => `/brands/${id}/edit`,
  editCategory: (id: string) => `/categories/${id}/edit`,
  editProduct: (id: string) => `/products/${id}/edit`,
} as const;

export type RouteKey = keyof typeof routes;
