import {
  Archive,
  ArrowLeft,
  ArrowUpRight,
  BadgePercent,
  BarChart3,
  Bell,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  Code,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Eye,
  FileText,
  FilterX,
  Folder,
  FolderPlus,
  Gift,
  Globe,
  GripVertical,
  History,
  ImageIcon,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  List,
  ListTree,
  LogOut,
  type LucideIcon,
  Mail,
  Menu,
  MessageCircle,
  Moon,
  Package,
  PackagePlus,
  PanelLeft,
  Pencil,
  Phone,
  Plus,
  Receipt,
  RefreshCcw,
  Save,
  Search,
  SearchX,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Star,
  Store,
  Sun,
  Trash2,
  Truck,
  Upload,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react";

type IconProps = {
  className?: string;
  name: string;
};

const icons: Record<string, LucideIcon> = {
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-up-right": ArrowUpRight,
  "badge-percent": BadgePercent,
  "bar-chart-3": BarChart3,
  bell: Bell,
  calendar: Calendar,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-up-down": ChevronsUpDown,
  "circle-alert": CircleAlert,
  code: Code,
  "credit-card": CreditCard,
  database: Database,
  "dollar-sign": DollarSign,
  download: Download,
  eye: Eye,
  "file-text": FileText,
  "filter-x": FilterX,
  folder: Folder,
  "folder-plus": FolderPlus,
  gift: Gift,
  globe: Globe,
  "grip-vertical": GripVertical,
  history: History,
  image: ImageIcon,
  inbox: Inbox,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  list: List,
  "list-tree": ListTree,
  "log-out": LogOut,
  mail: Mail,
  menu: Menu,
  "message-circle": MessageCircle,
  moon: Moon,
  package: Package,
  "package-plus": PackagePlus,
  "panel-left": PanelLeft,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  receipt: Receipt,
  "refresh-ccw": RefreshCcw,
  save: Save,
  search: Search,
  "search-x": SearchX,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "sliders-horizontal": SlidersHorizontal,
  star: Star,
  store: Store,
  sun: Sun,
  "trash-2": Trash2,
  truck: Truck,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  x: X,
};

export function Icon({ className, name }: IconProps) {
  const LucideIconComponent = icons[name] ?? Settings;

  return (
    <LucideIconComponent
      aria-hidden="true"
      className={className}
      strokeWidth={2}
    />
  );
}
