export const GCS_IMAGE_STORAGE_KB = 1000;

export const GCS_IMAGE_COMPRESS_MAX_BYTES = 800 * GCS_IMAGE_STORAGE_KB;

export const GCS_IMAGE_COMPRESS_MIN_BYTES = 400 * GCS_IMAGE_STORAGE_KB;

export const GCS_IMAGE_COMPRESS_THRESHOLD_BYTES = GCS_IMAGE_COMPRESS_MAX_BYTES;

export const GCS_IMAGE_COMPRESS_MIN_LABEL = "400 KB";

export const GCS_IMAGE_COMPRESS_MAX_LABEL = "800 KB";
