export const ModalName = {
  cartSidebar: "cartSidebar",
  comparePanel: "comparePanel",
  categorySidebar: "categorySidebar",
  mobileMenu: "mobileMenu",
  offerSideMenu: "offerSideMenu",
  addedcomparisonModal: "addedcomparisonModal",
  quickViewModal: "quickViewModal",
  compareReviewModal: "compareReviewModal",
  wishlistModal: "wishlistModal",
  socialShareModal: "socialShareModal",
  notifyModal: "notifyModal",
  quickViewSizeGuideModal: "quickViewSizeGuideModal",
  signinModal: "signinModal",
  signupModal: "signupModal",
  instaModal: "instaModal",
  "recent-viewModal": "recent-viewModal",
  findStoreModal: "findStoreModal",
  requestDemoModal: "requestDemoModal",
  quickviewEditCartModal: "quickviewEditCartModal",
  addedCartModal: "addedCartModal",
  "popup-cartModal": "popup-cartModal",
  addPaymentMethodModal: "addPaymentMethodModal",
  alternateDeliveryAddressEditModal: "alternateDeliveryAddressEditModal",
  basicInfoEditModal: "basicInfoEditModal",
  contactInfoEditModal: "contactInfoEditModal",
  deliveryAddressEditModal: "deliveryAddressEditModal",
  "demos-modal": "demos-modal",
  passwordEditModal: "passwordEditModal",
  leaveReviewModal: "leaveReviewModal",
  makecallModal: "makecallModal",
  newsletterModal: "newsletterModal",
  welcomebannerModal: "welcomebannerModal",
  exampleModal: "exampleModal",
  couponSelectionModal: "couponSelectionModal",
  "rbt-content-modal-1": "rbt-content-modal-1",
  "rbt-content-modal-2": "rbt-content-modal-2",
  "rbt-content-modal-3": "rbt-content-modal-3",
  "rbt-content-modal-4": "rbt-content-modal-4",
  "rbt-content-modal-6": "rbt-content-modal-6",
} as const;

export type ModalNameType = (typeof ModalName)[keyof typeof ModalName];
